### ISSUE TITLE
Solr validation should use new validation class

### ISSUE THREAD

**Issue by szendeh** [MITLibraries/kepler#22]
- use http://python-jsonschema.readthedocs.org/en/latest/validate/

- schema doc (https://github.com/geoblacklight/geoblacklight-schema/blob/schemata/geoblacklight-schema.json) will be hosted... somewhere

**Comment by szendeh** [comment]
- possibly accommodate  multiple schemas?

**Comment by gravesm** [comment]
I think we will only need to support one schema.

**Comment by szendeh** [comment]
It’s not engineered until it’s over-engineered.

**Comment by szendeh** [comment]
The goeblacklight schema seems to require ‘layer_modified_dt’ field, but I’m not seeing that being explicitly set when we parse using FgdcParser.

Looking through the FGDC file, I'm not seeing a particular datestamp that I could confidently say is the correct one to associate with that field. Any suggestions welcome!

**Comment by gravesm** [comment]
This field has a default value of arrow.now(): https://github.com/MITLibraries/kepler/blob/master/kepler/records.py#L54

**Comment by szendeh** [comment]
Derp, I mis-read the test error. I thought it was claiming there was no value, but nope. Sorry, my bad.
