### ISSUE TITLE
Failed jobs should show the failed message

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/kepler#73]

**Comment by JPrevost** [comment]
Is the message already logged and just needs to be displayed in a View?

**Comment by gravesm** [comment]
Logging...uh, yeah, I'll create a ticket for that.

The idea here is that if a job fails we need to know why it failed. It should be displayed in the interface because hopefully someone other than me will be able to look at it and fix what needs to be fixed before resubmitting.
