### ISSUE TITLE
manage.py needs to support local and heroku

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/kepler#82]
It is not currently in a state that easily supports working with this in dev and deploying to heroku. The heroku config needs to be passed to the app factory when deploying.

**Comment by JPrevost** [comment]
Do you think using something like https://github.com/nickstenning/honcho would help bridge the gap?

**Comment by gravesm** [comment]
Hmm, yeah, that might work.

**Comment by JPrevost** [comment]
Hmmmm. 

Maybe all we need to do is run local via `heroku local`?:
https://devcenter.heroku.com/articles/getting-started-with-python-o

**Comment by gravesm** [comment]
I guess I'm mostly concerned with how configuration is managed. Sure, I can run it with heroku local, but how do I pass my development settings into it? It's burdensome to have to manage all those configuration settings as separate environment variables in dev. Flask configuration typically is done through a settings file, which isn't really how heroku does it.

**Comment by JPrevost** [comment]
Gotcha. I'm fine with a `.env` for stuff like that which we could have settings load from if it exists maybe.

**Comment by gravesm** [comment]
Yeah, honcho probably looks like our best option here.

**Comment by JPrevost** [comment]
Or foreman if you don't mind relying on ruby to launch your python app ;)
